/**
 * `argo design emit-shims` — generate the host-side walker shims from
 * .claude/argo.json. Shims are the decision-14 glue: THIN glob-map files at
 * `<app>/test/spec-diff/` and `<app>/test/vrt/` that hand already-imported
 * modules to the @argohq/toolkit/walkers factories. The factory owns the walk +
 * assertions, so a kit upgrade updates every host's gate logic without
 * re-templating, and a host-side rename can't fork it.
 *
 * Per-app knobs live in `design.<app>.walkers` (all optional):
 *   storiesGlob            default `../../<componentsPath>/**\/*.stories.{js,jsx,ts,tsx}`
 *   specsGlob              default `../../design/specs/**\/*.json`
 *   baselinesGlob          default `../../design/screenshots/**\/*.png`
 *   storybookTestPackage   default '@storybook/react'; null → storybook-free
 *                          identity composeStories (fixtures, non-storybook hosts)
 * Globs are relative to the shim's own directory (two levels below the app root).
 */

import { mkdirSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { findArgoJson } from '../../../config/argo-json.js'

const SHIM_FILES: Record<string, string> = {
  specDiff: 'test/spec-diff/spec-diff.walker.spec-diff.js',
  vrt: 'test/vrt/vrt.walker.vrt.js',
}

const GENERATED_BANNER = (kind: string) => `/**
 * Host-side ${kind} shim — GENERATED by \`argo design emit-shims\` from
 * .claude/argo.json (design.<app>.walkers); re-run the verb instead of
 * hand-editing. Passes already-imported glob maps to the kit factory
 * (decision 14): the factory owns the walk, so a rename can't fork the gate.
 */`

function composePrelude(storybookTestPackage: string | null): string {
  return storybookTestPackage === null
    ? `const composeStories = (storyModule) => ({ ...storyModule }) // storybook-free host`
    : `import { composeStories } from '${storybookTestPackage}'`
}

export function renderSpecDiffShim({
  storiesGlob,
  specsGlob,
  storybookTestPackage
}: { storiesGlob: string; specsGlob: string; storybookTestPackage: string | null }): string {
  return `${GENERATED_BANNER('spec-diff')}
import { runSpecDiffWalker } from '@argohq/toolkit/walkers'
${composePrelude(storybookTestPackage)}

const stories = import.meta.glob('${storiesGlob}', { eager: true })
const specs = import.meta.glob('${specsGlob}', { eager: true })

// Specs pair with stories by basename: <name>.stories.<ext> ↔ <name>.stories.json.
const specByBase = Object.fromEntries(
  Object.entries(specs).map(([path, mod]) => [path.split('/').pop().replace(/\\.json$/, ''), mod.default ?? mod])
)
const specsByComponent = Object.fromEntries(
  Object.keys(stories).map((path) => [path, specByBase[path.split('/').pop().replace(/\\.[cm]?[jt]sx?$/, '')]])
)

runSpecDiffWalker({ stories, specsByComponent, composeStories })
`
}

export function renderVrtShim({
  storiesGlob,
  baselinesGlob,
  storybookTestPackage
}: { storiesGlob: string; baselinesGlob: string; storybookTestPackage: string | null }): string {
  return `${GENERATED_BANNER('VRT')}
import { runVrtWalker } from '@argohq/toolkit/walkers'
${composePrelude(storybookTestPackage)}

const stories = import.meta.glob('${storiesGlob}', { eager: true })
const committedBaselines = import.meta.glob('${baselinesGlob}')

runVrtWalker({ stories, composeStories, committedBaselines })
`
}

export function shimOptions(block: Record<string, any>) {
  const walkers = block.walkers ?? {}
  return {
    storiesGlob: walkers.storiesGlob ?? `../../${block.componentsPath}/**/*.stories.{js,jsx,ts,tsx}`,
    specsGlob: walkers.specsGlob ?? '../../design/specs/**/*.json',
    baselinesGlob: walkers.baselinesGlob ?? '../../design/screenshots/**/*.png',
    storybookTestPackage: 'storybookTestPackage' in walkers ? walkers.storybookTestPackage : '@storybook/react',
  }
}

export function runEmitShims({ hostRoot = process.cwd() }: { hostRoot?: string } = {}) {
  if (!existsSync(join(hostRoot, '.claude', 'argo.json'))) {
    throw new Error(`emit-shims: no .claude/argo.json under ${hostRoot} — run argo init first`)
  }
  const found = findArgoJson(hostRoot)
  const apps: { appKey: string; files: string[] }[] = []
  for (const [appKey, block] of Object.entries(found?.config?.design ?? {})) {
    if (typeof block.componentsPath !== 'string') continue // inert block — nothing to walk yet
    const appRoot = join(hostRoot, block.root ?? appKey)
    const options = shimOptions(block)
    const files: string[] = []
    for (const [kind, rel] of Object.entries(SHIM_FILES)) {
      const target = join(appRoot, rel)
      mkdirSync(dirname(target), { recursive: true })
      writeFileSync(target, kind === 'specDiff' ? renderSpecDiffShim(options) : renderVrtShim(options))
      files.push(rel)
    }
    apps.push({ appKey, files })
  }
  return { apps }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2)
  const i = args.indexOf('--host-root')
  const report = runEmitShims({ hostRoot: i === -1 ? process.cwd() : args[i + 1] })
  console.log(JSON.stringify(report))
  process.exit(0)
}
