#!/usr/bin/env node

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { findDesignBlock } from '../audit/prepare-design-rules-audit-options.js'

type TokenVariable = {
  id?: string
  name: string
  description?: string
  valuesByMode?: Record<string, unknown>
  values?: Record<string, unknown>
}

type TokenCollection = {
  name: string
  modes?: unknown[]
  variables?: TokenVariable[]
}

type TokensDump = { collections?: TokenCollection[] }

function isAlias(value: unknown): value is { type: string; id: string } {
  return Boolean(value && typeof value === 'object' && (value as any).type === 'VARIABLE_ALIAS' && typeof (value as any).id === 'string')
}

/** The variable's default-mode value — figma-sync dumps `valuesByMode` keyed by modeId; `values` is accepted as a lenient synonym. */
function defaultModeValue(variable: TokenVariable): unknown {
  const byMode = variable.valuesByMode ?? variable.values
  if (!byMode || typeof byMode !== 'object') return undefined
  return Object.values(byMode)[0]
}

/**
 * Pure generation (unit-tested): tokens dump in, markdown out. Groups the
 * Semantic collection's variables by their `<prefix>/` path segment (e.g.
 * `button/`, `surface/`; un-prefixed names group last under `(ungrouped)`),
 * one line per variable. The trailing clause is the variable's description
 * when it has one, else the NAME of the primitive it aliases in its default
 * mode (resolved against every variable in the dump by id), else nothing.
 */
export function generateTokenManifest(tokens: TokensDump, { semanticCollectionName = 'Semantic' }: { semanticCollectionName?: string } = {}) {
  const collections = tokens?.collections ?? []
  const semantic = collections.find((c) => c?.name === semanticCollectionName)
  if (!semantic) {
    throw new Error(`generate-token-manifest: no "${semanticCollectionName}" collection in tokens.json (found: ${collections.map((c) => c?.name).join(', ') || 'none'})`)
  }

  const variableNameById = new Map<string, string>()
  for (const collection of collections) {
    for (const variable of collection.variables ?? []) {
      if (variable.id) variableNameById.set(variable.id, variable.name)
    }
  }

  const groups = new Map<string, string[]>()
  for (const variable of semantic.variables ?? []) {
    const slash = variable.name.indexOf('/')
    const prefix = slash === -1 ? '(ungrouped)' : `${variable.name.slice(0, slash)}/`

    let clause = variable.description?.trim()
    if (!clause) {
      const value = defaultModeValue(variable)
      if (isAlias(value)) clause = variableNameById.get(value.id)
    }

    const line = clause ? `- ${variable.name} — ${clause}` : `- ${variable.name}`
    if (!groups.has(prefix)) groups.set(prefix, [])
    groups.get(prefix)!.push(line)
  }

  const sortedPrefixes = [...groups.keys()].sort((a, b) =>
    a === '(ungrouped)' ? 1 : b === '(ungrouped)' ? -1 : a.localeCompare(b)
  )

  const sections = sortedPrefixes.map((prefix) => [`## ${prefix}`, ...groups.get(prefix)!].join('\n'))
  return [
    `# ${semanticCollectionName} token manifest`,
    '',
    'Generated by `argo design generate-token-manifest` from design/tokens.json — never hand-edit.',
    'These variables are the complete design-token vocabulary for authoring in Figma.',
    '',
    sections.join('\n\n'),
    ''
  ].join('\n')
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const cwd = process.cwd()
  const tokensPath = join(cwd, 'design', 'tokens.json')
  if (!existsSync(tokensPath)) {
    console.error(`generate-token-manifest: ${tokensPath} not found — run figma-sync's token dump first`)
    process.exit(1)
  }

  let tokens: TokensDump
  try {
    tokens = JSON.parse(readFileSync(tokensPath, 'utf8'))
  } catch {
    console.error('generate-token-manifest: design/tokens.json is not valid JSON')
    process.exit(1)
  }

  const designBlock = findDesignBlock(cwd)
  const semanticCollectionName = designBlock?.semanticCollectionName ?? 'Semantic'

  let manifest: string
  try {
    manifest = generateTokenManifest(tokens!, { semanticCollectionName })
  } catch (err: any) {
    console.error(err.message)
    process.exit(1)
  }

  const outPath = join(cwd, 'design', 'semantic-manifest.md')
  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, manifest!, 'utf8')
  console.log(JSON.stringify({ outPath, lines: manifest!.split('\n').length }))
}
